### ISSUE TITLE
Use 308 for redirects from wrong trailing-slash endpoints

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api#66] opened 2021-01-25 23:00 UTC
Could be a user (ie my) error, but
```
*(Pdb) p requests.put(url, json=json, headers=self._headers).text
'{"name":["This field is required."]}'
(Pdb) p json
{'metadata': {'description': "upload on 00009 failed first with 401 and now with 400. Let's try on a brand new one", 'name': 'test10', 'identifier': {'propertyID': 'DANDI', 'value': '000009'}}, 'name': 'test10'}
(Pdb) p url
'https://api.dandiarchive.org/api/dandisets/000009/versions/draft'
```
so I do provide name in the json record to requests' `put`. Metadata has that name as well, so all should be "kosher" but API isn't happy

**Comment by yarikoptic** [comment] 2021-01-25 23:11
hm... when I do it via swagger, that works... khm... DAMN -- it is the training `/` in the url which was missing.

Could may be API somehow be resilient or at least suggestive of what am I doing wrong?

**Comment by dchiquit** [comment] 2021-01-26 00:34
Looks like that request returned a 301 permanent redirect, which I think is reasonable response. Sadly it doesn't come across very well unless you're logging the response code + response body.

**Comment by yarikoptic** [comment] 2021-01-26 01:32
Hmm, will need to check more how I ended up with `'{"name":["This field is required."]}'` , suggesting that may be requests did follow the redirect but didn't provide the same data?

**Comment by dchiquit** [comment] 2021-01-26 14:41
That seems unlikely, but I don't know how else that would have happened. I don't have timestamps for the request you tried, but when I tried to cURL the same endpoint, it gave me a 301.

**Comment by yarikoptic** [comment] 2021-01-26 15:44
It does return 401, but if I would tell curl to follow (`-L`), I get exactly that return value:
<details>
<summary>example</summary> 

```shell
$> curl -v -L -H "Authorization: token $token" -X PUT "https://api.dandiarchive.org/api/dandisets/000009/versions/draft" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: YYY" -d "{  \"metadata\": {\"description\": \"upload on 00009 failed first with 401 and now with 400. Let's try on a brand new one\", \"name\": \"test10\", \"identifier\": {\"propertyID\": \"DANDI\", \"value\": \"000009\"}},  \"name\": \"test10\"}"
*   Trying 107.21.11.91:443...
* Connected to api.dandiarchive.org (107.21.11.91) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=api.dandiarchive.org
*  start date: Jan  1 23:08:54 2021 GMT
*  expire date: Apr  1 23:08:54 2021 GMT
*  subjectAltName: host "api.dandiarchive.org" matched cert's "api.dandiarchive.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> PUT /api/dandisets/000009/versions/draft HTTP/1.1
> Host: api.dandiarchive.org
> User-Agent: curl/7.72.0
> Authorization: token XXX
> accept: application/json
> Content-Type: application/json
> X-CSRFToken: YYY
> Content-Length: 214
> 
* upload completely sent off: 214 out of 214 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Connection: keep-alive
< Server: gunicorn/20.0.4
< Date: Tue, 26 Jan 2021 15:43:16 GMT
< Content-Type: text/html; charset=utf-8
< Location: /api/dandisets/000009/versions/draft/
< Content-Length: 0
< Vary: Origin
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< Via: 1.1 vegur
< 
* Connection #0 to host api.dandiarchive.org left intact
* Issue another request to this URL: 'https://api.dandiarchive.org/api/dandisets/000009/versions/draft/'
* Switch from POST to GET
* Found bundle for host api.dandiarchive.org: 0x56215087c260 [serially]
* Can not multiplex, even if we wanted to!
* Re-using existing connection! (#0) with host api.dandiarchive.org
* Connected to api.dandiarchive.org (107.21.11.91) port 443 (#0)
> PUT /api/dandisets/000009/versions/draft/ HTTP/1.1
> Host: api.dandiarchive.org
> User-Agent: curl/7.72.0
> Authorization: token XXX
> accept: application/json
> Content-Type: application/json
> X-CSRFToken: YYY
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Connection: keep-alive
< Server: gunicorn/20.0.4
< Date: Tue, 26 Jan 2021 15:43:16 GMT
< Content-Type: application/json
< Vary: Accept, Cookie, Origin
< Allow: GET, PUT, HEAD, OPTIONS
< X-Frame-Options: DENY
< Content-Length: 36
< Strict-Transport-Security: max-age=31536000
< X-Content-Type-Options: nosniff
< Via: 1.1 vegur
< 
* Connection #0 to host api.dandiarchive.org left intact
{"name":["This field is required."]}%  
```
</details>

**Comment by yarikoptic** [comment] 2021-01-26 15:47
ha, may be because of `Switch from POST to GET` - why is that so?  may be redirects aren't "sufficient" (i.e. PUT cannot be redirected?) in such cases... dunno this http machinery well

**Comment by dchiquit** [comment] 2021-01-26 16:25
Looks like cURL's redirect follower did not include the content. The first PUT had a `Content-Length` of 214, but the second one didn't have a `Content-Length` at all, which seems to imply that no body was sent.

**Comment by yarikoptic** [comment] 2021-01-26 17:20
so possibly requests is also having the same  behavior... may be that is how redirects are "formalized" to work?  if so, no redirects should be used I guess and either endpoints allow for invocation without `/` or error out informatively ("use with trailing /")

**Comment by dchiquit** [comment] 2021-01-27 21:55
That setting [can be turned off globally](https://docs.djangoproject.com/en/dev/ref/settings/#append-slash), but I would prefer to keep the redirects unless they are impeding a feature. It looks redirect behavior is designed to not forward the request body to the secondary location to protect unsafe operations (PUT/POST/PATCH/DELETE) from being applied unintentionally or from happening twice, which is good. I find redirects helpful for GETs, and for trying to visit https://api.dandiarchive.org/swagger or similar URLs. 

If this is a frequent and recurring problem we can always disable it, but to me this doesn't seem like a frequent problem.

**Comment by yarikoptic** [comment] 2021-01-28 13:52
Thanks!  It is indeed infrequent, **but** IMHO they bring us inconsistency (between GET-vs-other methods) and may be (unlikely) danger of invoking undesired command. Inconsistency: they would workout nicely for a user who `GET /something` (whenever should have been `/something/`) but then user would try `PUT /something` and it would fail (without clear error message). Danger: may be some PUT/DELETE etc call would have only optional parameters, and thus redirected call would may be even succeed, but operating incorrectly.

So, I would have preferred to flip it, "I would prefer to disable redirects unless they add a useful feature" ;)  But also it might be worth checking how other popular APIs operate on a missing `/` -- do they redirect? fail? have it optional?

**Comment by dchiquit** [comment] 2021-01-29 15:19
https://github.com/girder/django-composed-configuration/issues/113 should hopefully address your issue upstream. The intended behavior of 301 redirects is to modify the request to prevent unsafe operations. The newer code 308 will redirect without modifications.

We are using `django-composed-configurations` to configure `dandi-api`, so I can work on that issue to always use 308 for redirects.

**Comment by waxlamp** [comment] 2021-12-29 23:24
We have a good proposed solution to this issue (to use 308 in place of 301). My question is, do we want to actually execute it? Thoughts, @dchiquito, @brianhelba, @yarikoptic?

My own thoughts are that we should just close this issue as `wontfix`. I agree it's annoying to receive a cryptic error condition due to non-GET requests not porting their request bodies to the redirect target, but that is by design. It's easily fixed by learning that you must include the trailing `/`, so we would be changing a global behavior just to serve a one-off manual use case (we are killing a mosquito with a bazooka). The downside of this is a loss in performance, as clients invoking the "wrong" version of the API endpoint have to make two trips to get their work done.

**Comment by dchiquito** [comment] 2022-01-03 21:01
Quoting Brian from https://github.com/girder/django-composed-configuration/issues/113:
> We want it to send a 308. I think the solution is to add a new subclass of HttpResponseRedirectBase which has a status_code = 308. Then, we should subclass CommonMiddleware and set response_redirect_class of that. Finally, in the settings, switch out the old CommonMiddleware for the new subclassesed version.
>
> I'd be ok with upstreaming to Girder 4 this as well, since it makes sense for all projects to redirect with 308.

I think fixing this upstream would be the best solution.

**Comment by waxlamp** [comment] 2022-01-03 23:20
> I think fixing this upstream would be the best solution.

In that case, closing this in favor of https://github.com/girder/django-composed-configuration/issues/113.

**Closed by waxlamp** 2022-01-03 23:20 UTC
